// AUTO-GENERATE: ESP32 用 C++ ヘッダ (constants + helper)
// 出力: firmware-esphome/contract.generated.h (gitignore)

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CONTRACT_VERSION,
  TIMESTAMP_HEADER,
  SIGNATURE_HEADER,
} from "../src/envelope.js";
import { CHANNELS } from "../src/payload.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "../../");
const OUT_PATH = resolve(REPO_ROOT, "firmware-esphome/contract.generated.h");

const channelArray = CHANNELS.map((c) => `  "${c}"`).join(",\n");

const header = `// AUTO-GENERATED by contract/codegen/emit-c-header.ts — DO NOT EDIT
// Yakiimo Ingest Contract (Envelope + Payload Schema) v${CONTRACT_VERSION}
//
// Source of truth: contract/src/envelope.ts と contract/src/payload.ts
// 再生成: npm run codegen (リポルートで実行)
#pragma once

#include <string>

#define YAKIIMO_CONTRACT_VERSION ${CONTRACT_VERSION}
#define YAKIIMO_TIMESTAMP_HEADER "${TIMESTAMP_HEADER}"
#define YAKIIMO_SIGNATURE_HEADER "${SIGNATURE_HEADER}"

// 5 つの channel 名 (Payload Schema)。
constexpr const char* YAKIIMO_CHANNELS[] = {
${channelArray}
};
constexpr int YAKIIMO_CHANNELS_COUNT = ${CHANNELS.length};

// 署名対象メッセージを構築する。
// 形式: \`\${version}\\n\${timestamp_unix_sec}\\n\${body}\`
//
// 注: 引数は unsigned long long (64-bit)。ESP32 firmware (Arduino-ESP32) の
// time_t は signed 32-bit ゆえ 2038-01-19 にラップする (詳細は ADR-0002)。
// ここでは内部一貫性 (header timestamp と HMAC message timestamp の cast 幅
// 統一) のみ確保し、根治は framework 64-bit time_t 採用待ち。
inline std::string yakiimo_build_signed_message(unsigned long long timestamp_unix_sec, const std::string& body) {
  return std::to_string(YAKIIMO_CONTRACT_VERSION) + "\\n" + std::to_string(timestamp_unix_sec) + "\\n" + body;
}
`;

writeFileSync(OUT_PATH, header, "utf8");
console.log(`[codegen] wrote ${OUT_PATH}`);
