// AUTO-GENERATE: Supabase 用 SQL 関数群
// 出力: supabase/migrations/007_contract_functions.sql (commit)

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CHANNELS,
  DEVICE_ID_REGEX,
  SESSION_ID_REGEX,
  TEMP_C_RANGE,
  HUMIDITY_PCT_RANGE,
  PRESSURE_HPA_RANGE,
  MEASURED_AT_PAST_INTERVAL,
  MEASURED_AT_FUTURE_INTERVAL,
} from "../src/payload.js";
import { CONTRACT_VERSION } from "../src/envelope.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "../../");
const OUT_PATH = resolve(REPO_ROOT, "supabase/migrations/007_contract_functions.sql");

const channelLiteralList = CHANNELS.map((c) => `'${c}'`).join(",");
const deviceIdRegexSrc = DEVICE_ID_REGEX.source;
const sessionIdRegexSrc = SESSION_ID_REGEX.source;

const sql = `-- AUTO-GENERATED by contract/codegen/emit-sql-functions.ts — DO NOT EDIT
-- Yakiimo Ingest Contract (Payload Schema) v${CONTRACT_VERSION}
--
-- Source of truth: contract/src/payload.ts
-- 再生成: npm run codegen (リポルートで実行)
--
-- 各関数は CREATE OR REPLACE で冪等。BEFORE INSERT trigger と RLS WITH CHECK
-- いずれからも呼べる。internal schema 配下に置き public 露出を避ける。

BEGIN;

CREATE SCHEMA IF NOT EXISTS internal;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_channel(c text) RETURNS boolean
  LANGUAGE sql IMMUTABLE
  SET search_path = pg_catalog
  AS $$
    SELECT c IN (${channelLiteralList})
$$;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_device_id(d text) RETURNS boolean
  LANGUAGE sql IMMUTABLE
  SET search_path = pg_catalog
  AS $$
    SELECT d ~ '${deviceIdRegexSrc}'
$$;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_session_id(s text) RETURNS boolean
  LANGUAGE sql IMMUTABLE
  SET search_path = pg_catalog
  AS $$
    SELECT s ~ '${sessionIdRegexSrc}'
$$;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_measured_at(t timestamptz) RETURNS boolean
  LANGUAGE sql STABLE
  SET search_path = pg_catalog
  AS $$
    SELECT t > now() - interval '${MEASURED_AT_PAST_INTERVAL}'
       AND t < now() + interval '${MEASURED_AT_FUTURE_INTERVAL}'
$$;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_temp(v real) RETURNS boolean
  LANGUAGE sql IMMUTABLE
  SET search_path = pg_catalog
  AS $$
    SELECT v IS NULL OR (v >= ${TEMP_C_RANGE.min} AND v <= ${TEMP_C_RANGE.max})
$$;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_humidity(v real) RETURNS boolean
  LANGUAGE sql IMMUTABLE
  SET search_path = pg_catalog
  AS $$
    SELECT v IS NULL OR (v >= ${HUMIDITY_PCT_RANGE.min} AND v <= ${HUMIDITY_PCT_RANGE.max})
$$;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_pressure(v real) RETURNS boolean
  LANGUAGE sql IMMUTABLE
  SET search_path = pg_catalog
  AS $$
    SELECT v IS NULL OR (v >= ${PRESSURE_HPA_RANGE.min} AND v <= ${PRESSURE_HPA_RANGE.max})
$$;

COMMIT;

-- ROLLBACK (実行不要・参考):
-- BEGIN;
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_channel(text);
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_device_id(text);
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_session_id(text);
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_measured_at(timestamptz);
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_temp(real);
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_humidity(real);
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_pressure(real);
-- COMMIT;
`;

writeFileSync(OUT_PATH, sql, "utf8");
console.log(`[codegen] wrote ${OUT_PATH}`);
