// AUTO-GENERATE: 公開仕様書 (Markdown)
// 出力: docs/CONTRACT.md (commit)

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CONTRACT_VERSION,
  TIMESTAMP_HEADER,
  SIGNATURE_HEADER,
  TIMESTAMP_TOLERANCE_PAST_SEC,
  TIMESTAMP_TOLERANCE_FUTURE_SEC,
} from "../src/envelope.js";
import {
  CHANNELS,
  DEVICE_ID_REGEX,
  SESSION_ID_REGEX,
  TEMP_C_RANGE,
  HUMIDITY_PCT_RANGE,
  PRESSURE_HPA_RANGE,
  MEASURED_AT_PAST_INTERVAL,
  MEASURED_AT_FUTURE_INTERVAL,
} from "../src/payload.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "../../");
const OUT_PATH = resolve(REPO_ROOT, "docs/CONTRACT.md");

const channelTable = CHANNELS.map((c) => `| \`${c}\` |`).join("\n");

const md = `<!-- AUTO-GENERATED by contract/codegen/emit-doc.ts — DO NOT EDIT -->
<!-- Source of truth: contract/src/envelope.ts と contract/src/payload.ts -->
<!-- 再生成: npm run codegen (リポルートで実行) -->

# Yakiimo Ingest Contract v${CONTRACT_VERSION}

ESP32 → Cloudflare Worker → Supabase の経路で交わされる契約の完全仕様。

ドメイン用語の定義は \`docs/CONTEXT.md\` を参照してください。

---

## Envelope (HMAC 認証層)

ESP32 が Worker に送る POST リクエストの認証情報。

### Headers

| Header | 内容 |
|--------|------|
| \`${TIMESTAMP_HEADER}\` | Unix epoch 秒 (整数) |
| \`${SIGNATURE_HEADER}\` | HMAC-SHA256 hex (64 chars, lowercase) |

### Message format (署名対象)

\`\`\`
\${version}\\n\${timestamp}\\n\${body}
\`\`\`

- \`version\` = ${CONTRACT_VERSION} (現行)
- \`timestamp\` = Unix epoch 秒
- \`body\` = HTTP POST body (UTF-8 JSON 文字列)

### Timestamp tolerance

Worker は以下のウィンドウ外の timestamp を拒否します:

| 方向 | 許容 |
|------|------|
| 過去 | ${TIMESTAMP_TOLERANCE_PAST_SEC} 秒 |
| 未来 | ${TIMESTAMP_TOLERANCE_FUTURE_SEC} 秒 |

### Signature

\`\`\`
HMAC-SHA256(secret, message)
\`\`\`

- secret は ESP32 \`secrets.yaml\` の \`ingest_hmac_secret\` と Cloudflare Worker secret \`INGEST_HMAC_SECRET\` で同値共有
- 推奨生成: \`openssl rand -hex 32\`

### Verify result

| Result | 条件 |
|--------|------|
| \`ok\` | version 一致 + timestamp 範囲内 + signature 一致 |
| \`version_unsupported\` | 未知の version |
| \`timestamp_out_of_range\` | tolerance 外 |
| \`signature_mismatch\` | HMAC 不一致 |

---

## Payload Schema (LogRow)

\`yakiimo_temp_logs\` に挿入される 1 行。POST body は LogRow の配列 (1 リクエスト = 5 ch 分の 5 行) です。

### Required fields

| Field | Type | Constraint |
|-------|------|------------|
| \`device_id\` | string | regex \`${DEVICE_ID_REGEX.source}\` |
| \`session_id\` | string | regex \`${SESSION_ID_REGEX.source}\` |
| \`measured_at\` | string | ISO 8601 UTC (例: \`2026-05-07T01:23:45Z\`) |
| \`channel\` | string | 下記 5 値のいずれか |
| \`temp_c\` | number \\| null | ${TEMP_C_RANGE.min} ≤ v ≤ ${TEMP_C_RANGE.max} |

### Channel domain

| Channel |
|---------|
${channelTable}

### Optional fields (env channel のみ)

| Field | Type | Constraint |
|-------|------|------------|
| \`humidity_pct\` | number \\| null | ${HUMIDITY_PCT_RANGE.min} ≤ v ≤ ${HUMIDITY_PCT_RANGE.max} |
| \`pressure_hpa\` | number \\| null | ${PRESSURE_HPA_RANGE.min} ≤ v ≤ ${PRESSURE_HPA_RANGE.max} |

非 env channel では \`humidity_pct\` / \`pressure_hpa\` は \`null\` に固定してください。

### measured_at の許容ウィンドウ (DB 側で強制)

| 方向 | 許容 |
|------|------|
| 過去 | ${MEASURED_AT_PAST_INTERVAL} |
| 未来 | ${MEASURED_AT_FUTURE_INTERVAL} |

---

## Plausibility validation について

本契約は **constraint level** (技術的に成立する範囲) のみを定義し、**plausibility level** (yakiimo として normal な値の窓) は意図的に含めません。詳細は \`docs/adr/0001-defer-plausibility-validation.md\` を参照してください。

---

## Defense in depth

| Layer | 場所 | 強制対象 |
|-------|------|---------|
| L1 (Envelope) | Cloudflare Worker | anon の不正アクセス全般 |
| L2 (Payload) | Cloudflare Worker | Worker 経由の INSERT 全て (validateLogRow) |
| L3 (DB trigger) | Supabase BEFORE INSERT | 全ロール (service_role 含む) |

L1 だけでは Worker bug / 設定ミスを catch できないため、L2 で Worker 自身が contract に従って validate し、L3 で DB 層が最終ゲートとなる構造です。
`;

writeFileSync(OUT_PATH, md, "utf8");
console.log(`[codegen] wrote ${OUT_PATH}`);
