-- AUTO-GENERATED by contract/codegen/emit-sql-functions.ts — DO NOT EDIT
-- Yakiimo Ingest Contract (Payload Schema) v1
--
-- Source of truth: contract/src/payload.ts
-- 再生成: npm run codegen (リポルートで実行)
--
-- 各関数は CREATE OR REPLACE で冪等。BEFORE INSERT trigger と RLS WITH CHECK
-- いずれからも呼べる。internal schema 配下に置き public 露出を避ける。

BEGIN;

CREATE SCHEMA IF NOT EXISTS internal;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_channel(c text) RETURNS boolean
  LANGUAGE sql IMMUTABLE
  SET search_path = pg_catalog
  AS $$
    SELECT c IN ('potato_internal','potato_surface','kiln_ambient','stone_surface','env')
$$;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_device_id(d text) RETURNS boolean
  LANGUAGE sql IMMUTABLE
  SET search_path = pg_catalog
  AS $$
    SELECT d ~ '^[a-z0-9_-]{1,32}$'
$$;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_session_id(s text) RETURNS boolean
  LANGUAGE sql IMMUTABLE
  SET search_path = pg_catalog
  AS $$
    SELECT s ~ '^[a-zA-Z0-9_-]{1,64}$'
$$;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_measured_at(t timestamptz) RETURNS boolean
  LANGUAGE sql STABLE
  SET search_path = pg_catalog
  AS $$
    SELECT t > now() - interval '5 minutes'
       AND t < now() + interval '1 hour'
$$;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_temp(v real) RETURNS boolean
  LANGUAGE sql IMMUTABLE
  SET search_path = pg_catalog
  AS $$
    SELECT v IS NULL OR (v >= -50 AND v <= 1500)
$$;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_humidity(v real) RETURNS boolean
  LANGUAGE sql IMMUTABLE
  SET search_path = pg_catalog
  AS $$
    SELECT v IS NULL OR (v >= 0 AND v <= 100)
$$;

CREATE OR REPLACE FUNCTION internal.yakiimo_valid_pressure(v real) RETURNS boolean
  LANGUAGE sql IMMUTABLE
  SET search_path = pg_catalog
  AS $$
    SELECT v IS NULL OR (v >= 800 AND v <= 1200)
$$;

COMMIT;

-- ROLLBACK (実行不要・参考):
-- BEGIN;
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_channel(text);
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_device_id(text);
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_session_id(text);
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_measured_at(timestamptz);
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_temp(real);
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_humidity(real);
-- DROP FUNCTION IF EXISTS internal.yakiimo_valid_pressure(real);
-- COMMIT;
